### ISSUE TITLE
HV-KB395L Keyboard

### ISSUE THREAD

**Issue by m1st0** [pbludov/hv-kb390l-config#3]
Any possibility to easily add this keyboard also? Vendor is the same, but product id is different:
Vendor="04d9"
Product="a1dd"

Would be simple enough to add the additional layout keys and code to recognize it?

**Comment by pbludov** [comment]
It is highly probable. The key settings are stored in a 6x21 matrix, but for HV-KB390L a 6x16 matrix is sufficient. Moreover, the backlight setting is clearly designed for RGB, but in HV-KB390L only the blue part is used. All this indicates that the keyboards differ only in the mechanical part, but may have the same controller.

@m1st0, if you have HV-KB395L, please give it a try. Build scripts can be found in `appveyor.yml` (windows), `.travis.yml` (ubuntu & mac os) and `buddy.yml` (many linux distros).

**Comment by m1st0** [comment]
It worked after adding a udev `uaccess` rule as well as switching the product id in _kb390l.cpp_ on my _kb395l_ branch.  You can see the diff, but of course it isn't ready to merge until I can get some suggestion of how you want me to go about naming and setup.  I can update the build scripts as well.  Should I copy off kb390l.cpp and kb390l.h to kb395l.cpp and kb395l.h?  Do more extensive renaming and determining somewhere which keyboard is attached? (My branch is just a test of functionality on Ubuntu 19.04.)

**Comment by m1st0** [comment]
As well, I got many effects to work except for some like _rain_.  I wonder if that is specific to the 390L or if there is more work to do.  Any effects not available default to wave.

**Comment by ksangwin** [comment]
I'd like to use this for my HV-KB395L board as well. When I attempt to run the software straight out of the apt-get, all the tabs are greyed out so I'm assuming @m1st0 's changes were never merged. So I guess I'll try implementing the changes locally myself and see how it goes.

**Comment by m1st0** [comment]
It has been some time. Let me know what you would like me to do to help. I
can revisit my copy tomorrow.

**Comment by pbludov** [comment]
> I'd like to use this for my HV-KB395L board as well. When I attempt to run the software straight out of the apt-get, all the tabs are greyed out so I'm assuming @m1st0 's changes were never merged. So I guess I'll try implementing the changes locally myself and see how it goes.

This model may need a little more change than just replacing the PID. At least it has more buttons. Without access to the body, I can't be helpful. Patches are welcome, of course.

**Comment by m1st0** [comment]
Abandoning due to age of issue and switching in keyboard. Mostly works for me in my old keyboard in any case.
